server:
  port: 9093

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: denizgumus1996@gmail.com
    password: zrrz chys sttt amcb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true