server:
  port: 9091
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfileDB
      username: bilge
      password: bilge!123

